name: Deploy to Production

# Déclenchement manuel uniquement
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    name: Deploy Plugin to OJS Server
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    # Étape 1: Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Étape 2: Préparer les fichiers pour déploiement
    - name: Prepare deployment files
      run: |
        echo "📦 Preparing plugin files for deployment..."
        
        # Créer un dossier temporaire
        mkdir -p deployment/premiumSubmissionHelper
        
        # Copier tous les fichiers nécessaires (exclure les fichiers de dev)
        rsync -av --progress . deployment/premiumSubmissionHelper/ \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='*.md' \
          --exclude='.gitignore'
        
        # Afficher la structure des fichiers
        echo "📂 Plugin structure:"
        find deployment/premiumSubmissionHelper -type f | head -20
        
    # Étape 3: Créer une archive
    - name: Create deployment archive
      run: |
        cd deployment
        tar -czf premiumSubmissionHelper.tar.gz premiumSubmissionHelper/
        echo "✅ Archive created: $(ls -lh premiumSubmissionHelper.tar.gz)"
        
    # Étape 4: Configurer SSH
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        echo "SSH configuration completed"
        
    # Étape 5: Tester la connexion SSH
    - name: Test SSH Connection
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        echo "🔌 Testing SSH connection..."
        ssh -o ConnectTimeout=10 $SSH_USER@$SSH_HOST "echo '✅ SSH connection successful'"
        
    # Étape 6: Backup existant (si présent)
    - name: Backup existing plugin
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        OJS_PATH: ${{ secrets.OJS_PATH }}
      run: |
        echo "💾 Creating backup of existing plugin..."
        ssh $SSH_USER@$SSH_HOST "
          if [ -d '$OJS_PATH/plugins/generic/premiumSubmissionHelper' ]; then
            sudo cp -r '$OJS_PATH/plugins/generic/premiumSubmissionHelper' '$OJS_PATH/plugins/generic/premiumSubmissionHelper.backup.$(date +%Y%m%d_%H%M%S)'
            echo '✅ Backup created successfully'
          else
            echo 'ℹ️  No existing plugin found, skipping backup'
          fi
        "
        
    # Étape 7: Déployer le plugin
    - name: Deploy Plugin
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        OJS_PATH: ${{ secrets.OJS_PATH }}
      run: |
        echo "🚀 Deploying plugin to server..."
        
        # Transférer l'archive
        scp deployment/premiumSubmissionHelper.tar.gz $SSH_USER@$SSH_HOST:/tmp/
        
        # Déployer sur le serveur
        ssh $SSH_USER@$SSH_HOST "
          cd /tmp
          
          # Supprimer l'ancien plugin
          sudo rm -rf '$OJS_PATH/plugins/generic/premiumSubmissionHelper'
          
          # Extraire le nouveau plugin
          tar -xzf premiumSubmissionHelper.tar.gz
          
          # Déplacer vers le bon dossier
          sudo mv premiumSubmissionHelper '$OJS_PATH/plugins/generic/'
          
          # Définir les bonnes permissions
          sudo chown -R www-data:www-data '$OJS_PATH/plugins/generic/premiumSubmissionHelper'
          sudo chmod -R 755 '$OJS_PATH/plugins/generic/premiumSubmissionHelper'
          
          # Nettoyer les fichiers temporaires
          rm -f premiumSubmissionHelper.tar.gz
          
          echo '✅ Plugin deployed successfully'
        "
        
    # Étape 8: Vérifier le déploiement
    - name: Verify Deployment
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        OJS_PATH: ${{ secrets.OJS_PATH }}
      run: |
        echo "🔍 Verifying deployment..."
        ssh $SSH_USER@$SSH_HOST "
          if [ -f '$OJS_PATH/plugins/generic/premiumSubmissionHelper/PremiumSubmissionHelperPlugin.php' ]; then
            echo '✅ Plugin main file exists'
            echo '📂 Plugin structure:'
            ls -la '$OJS_PATH/plugins/generic/premiumSubmissionHelper/'
          else
            echo '❌ Plugin deployment failed'
            exit 1
          fi
        "
        
    # Étape 9: Notification de succès
    - name: Deployment Success
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "📊 Deployment Summary:"
        echo "  • Environment: ${{ github.event.inputs.environment }}"
        echo "  • Branch: ${{ github.ref }}"
        echo "  • Commit: ${{ github.sha }}"
        echo "  • Deployed by: ${{ github.actor }}"
        echo "  • Time: $(date)"
