name: Deploy to Production

# Déclenchement manuel + automatique
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
  push:
    branches:
      - main                    # Déclenche sur push vers main
    tags:
      - 'v*'                   # Déclenche sur tags version (v1.0.0, v1.2.0, etc.)
    paths:
      - 'plugins/generic/premiumSubmissionHelper/**'  # Seulement si le plugin change

jobs:
  deploy:
    name: Deploy Plugin to OJS Server
    runs-on: ubuntu-latest
    environment: production  # Environment fixe, on détermine la logique dans les steps
    
    steps:
    # Déterminer l'environnement selon le déclencheur
    - name: Determine environment
      id: determine_env
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          echo "trigger=manual" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "environment=production" >> $GITHUB_OUTPUT
          echo "trigger=tag" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "environment=production" >> $GITHUB_OUTPUT
          echo "trigger=branch" >> $GITHUB_OUTPUT
        else
          echo "environment=production" >> $GITHUB_OUTPUT
          echo "trigger=fallback" >> $GITHUB_OUTPUT
        fi
        
    # Afficher les informations de déploiement
    - name: Show deployment info
      run: |
        echo "🚀 Deployment triggered by: ${{ steps.determine_env.outputs.trigger }}"
        echo "📍 Environment: ${{ steps.determine_env.outputs.environment }}"
        echo "🔗 Ref: ${{ github.ref }}"
        
    # Étape 1: Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Étape 2: Préparer les fichiers pour déploiement
    - name: Prepare deployment files
      run: |
        echo "📦 Preparing plugin files for deployment..."
        
        # Créer le dossier de destination
        mkdir -p deployment/premiumSubmissionHelper
        
        # Vérifier que le plugin existe
        if [ ! -d "plugins/generic/premiumSubmissionHelper" ]; then
          echo "❌ Plugin directory not found!"
          exit 1
        fi
        
        # Copier SEULEMENT les fichiers du plugin
        cp -r plugins/generic/premiumSubmissionHelper/* deployment/premiumSubmissionHelper/
        
        # Vérifier le contenu
        echo "📂 Plugin files to deploy:"
        ls -la deployment/premiumSubmissionHelper/
        echo ""
        echo "📊 Total files: $(find deployment/premiumSubmissionHelper -type f | wc -l)"
        
    # Étape 3: Créer une archive
    - name: Create deployment archive
      run: |
        cd deployment
        tar -czf premiumSubmissionHelper.tar.gz premiumSubmissionHelper/
        echo "✅ Archive created: $(ls -lh premiumSubmissionHelper.tar.gz)"
        
    # Étape 4: Configurer SSH
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        # Créer le dossier SSH
        mkdir -p ~/.ssh
        
        # Configurer la clé privée (ed25519 compatible)
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        # Ajouter l'hôte aux known_hosts
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        
        # Configurer SSH pour utiliser la clé ed25519
        echo "Host $SSH_HOST" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
        echo "  IdentitiesOnly yes" >> ~/.ssh/config
        chmod 600 ~/.ssh/config
        
        echo "🔑 SSH configuration completed"
        
    # Étape 5: Tester la connexion SSH
    - name: Test SSH Connection
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        echo "🔌 Testing SSH connection..."
        ssh -o ConnectTimeout=10 $SSH_USER@$SSH_HOST "echo '✅ SSH connection successful'"
        
    # Étape 6: Backup existant (si présent)
    - name: Backup existing plugin
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        OJS_PATH: ${{ secrets.OJS_PATH }}
      run: |
        echo "💾 Creating backup of existing plugin..."
        ssh $SSH_USER@$SSH_HOST "
          if [ -d '$OJS_PATH/plugins/generic/premiumSubmissionHelper' ]; then
            sudo cp -r '$OJS_PATH/plugins/generic/premiumSubmissionHelper' '$OJS_PATH/plugins/generic/premiumSubmissionHelper.backup.$(date +%Y%m%d_%H%M%S)'
            echo '✅ Backup created successfully'
          else
            echo 'ℹ️  No existing plugin found, skipping backup'
          fi
        "
        
    # Étape 7: Déployer le plugin
    - name: Deploy Plugin
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        OJS_PATH: ${{ secrets.OJS_PATH }}
      run: |
        echo "🚀 Deploying plugin to server..."
        
        # Transférer l'archive
        scp deployment/premiumSubmissionHelper.tar.gz $SSH_USER@$SSH_HOST:/tmp/
        
        # Déployer sur le serveur
        ssh $SSH_USER@$SSH_HOST "
          cd /tmp
          
          # Supprimer l'ancien plugin
          sudo rm -rf '$OJS_PATH/plugins/generic/premiumSubmissionHelper'
          
          # Extraire le nouveau plugin
          tar -xzf premiumSubmissionHelper.tar.gz
          
          # Déplacer vers le bon dossier
          sudo mv premiumSubmissionHelper '$OJS_PATH/plugins/generic/'
          
          # Définir les bonnes permissions
          sudo chown -R www-data:www-data '$OJS_PATH/plugins/generic/premiumSubmissionHelper'
          sudo chmod -R 755 '$OJS_PATH/plugins/generic/premiumSubmissionHelper'
          
          # Nettoyer les fichiers temporaires
          rm -f premiumSubmissionHelper.tar.gz
          
          echo '✅ Plugin deployed successfully'
        "
        
    # Étape 8: Vérifier le déploiement
    - name: Verify Deployment
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        OJS_PATH: ${{ secrets.OJS_PATH }}
      run: |
        echo "🔍 Verifying deployment..."
        ssh $SSH_USER@$SSH_HOST "
          if [ -f '$OJS_PATH/plugins/generic/premiumSubmissionHelper/PremiumSubmissionHelperPlugin.php' ]; then
            echo '✅ Plugin main file exists'
            echo '📂 Plugin structure:'
            ls -la '$OJS_PATH/plugins/generic/premiumSubmissionHelper/'
          else
            echo '❌ Plugin deployment failed'
            exit 1
          fi
        "
        
    # Étape 9: Notification de succès
    - name: Deployment Success
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "📊 Deployment Summary:"
        echo "  • Environment: ${{ steps.determine_env.outputs.environment }}"
        echo "  • Trigger: ${{ steps.determine_env.outputs.trigger }}"
        echo "  • Branch: ${{ github.ref }}"
        echo "  • Commit: ${{ github.sha }}"
        echo "  • Deployed by: ${{ github.actor }}"
        echo "  • Time: $(date)"